import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import products from "../products.json";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link
          rel="stylesheet"
          href="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.css"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Shopee!</a>
        </h1>

        <p className={styles.description}>
          Get started by Scrolling{" "}
          <code className={styles.code}>😁💕</code>
        </p>

        <div className={styles.grid}>
          {products.map((product) => {
            return (
              <div key={product.id} className={styles.card}>
                <h3>{product.title}</h3>
                <img src={product.image} alt={"Preview of ${product.title}"} />
                <p>{product.description}</p>
                <p>${product.price}</p>
                <p>
                  <button  className="snipcart-add-item"
                  data-item-id={product.image}
                  data-item-image={product.image}
                  data-item-name={product.title}
                  data-item-price={product.price}>Add to Cart</button>
                </p>
              </div>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <script
          async
          src="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.js"
        />
        <div hidden id="snipcart" data-api-key="NzE5NzQ4YTctOWQzNy00NDI0LTljMWEtZWQ5MzY3OTRkZTYwNjM3OTA1MjQxODIxNzE2NTYx" />
      </footer>
    </div>
  );
}
